services:
#  redis:
#    image: redis:7.4-alpine
#    ports:
#      - 6379:6379
#    environment:
#      ALLOW_EMPTY_PASSWORD: yes 

  noghost-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  noghost-mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - noghost-network
    volumes:
      - noghost-mongo-data:/data/db
      - ./noghost-mongo.js:/docker-entrypoint-initdb.d/noghost-mongo.js
    restart: always

  noghost-kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - noghost-zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: noghost-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://noghost-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  noghost-mongo-data:

networks:
  noghost-network:
    driver: bridge