services:
#  redis:
#    image: redis:7.4-alpine
#    ports:
#      - 6379:6379
#    environment:
#      ALLOW_EMPTY_PASSWORD: yes 

  ${projectName}-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  ${projectName}-mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - ${projectName}-network
    volumes:
      - ${projectName}-mongo-data:/data/db
      - ./${projectName}-mongo.js:/docker-entrypoint-initdb.d/${projectName}-mongo.js
    restart: always

  ${projectName}-kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - ${projectName}-zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${projectName}-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${projectName}-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  ${projectName}-mongo-data:

networks:
  ${projectName}-network:
    driver: bridge